import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "moment/locale/id";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="container mx-auto">{children}</div>
        <footer className="bg-zinc-400 text-white text-center">
          Jadwal Pildun 2022, Varker Learning
        </footer>
      </body>
    </html>
  );
}
